# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-22 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20180522_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtdetailrecord',
            name='total_accumulative_contract_price',
        ),
        migrations.RemoveField(
            model_name='districtdetailrecord',
            name='total_accumulative_process_payment',
        ),
        migrations.RemoveField(
            model_name='districtdetailrecord',
            name='total_current_month_contract_price',
        ),
        migrations.RemoveField(
            model_name='districtdetailrecord',
            name='total_current_month_process_payment',
        ),
    ]
