# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-23 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20180523_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='number',
        ),
    ]
