# Generated by Django 2.0.2 on 2018-03-04 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BigType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('big_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.BigType')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_month_contract_price', models.FloatField(blank=True, null=True)),
                ('current_month_progress_payment', models.FloatField(blank=True, null=True)),
                ('accumulative_contract_price', models.FloatField(blank=True, null=True)),
                ('accumulative_progress_payment', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistrictDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.District')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistrictDetailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_month_contract_price', models.FloatField(blank=True, null=True)),
                ('current_month_progress_payment', models.FloatField(blank=True, null=True)),
                ('accumulative_contract_price', models.FloatField(blank=True, null=True)),
                ('accumulative_progress_payment', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.District')),
                ('district_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.DistrictDetail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistrictRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_month_contract_price', models.FloatField(blank=True, null=True)),
                ('current_month_progress_payment', models.FloatField(blank=True, null=True)),
                ('accumulative_contract_price', models.FloatField(blank=True, null=True)),
                ('accumulative_progress_payment', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.District')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField(blank=True, default=1.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('begin', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=64, null=True)),
                ('contract_unit_price', models.FloatField(blank=True, null=True)),
                ('current_month_project_quantities', models.FloatField(blank=True, null=True)),
                ('current_month_contract_price', models.FloatField(blank=True, null=True)),
                ('current_month_progress_payment', models.FloatField(blank=True, null=True)),
                ('accumulative_project_quantities', models.FloatField(blank=True, null=True)),
                ('accumulative_contract_price', models.FloatField(blank=True, null=True)),
                ('accumulative_progress_payment', models.FloatField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.District')),
                ('district_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.DistrictDetail')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Measurement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Organization')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Project')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.Phase')),
            ],
        ),
        migrations.AddField(
            model_name='districtrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Organization'),
        ),
        migrations.AddField(
            model_name='districtrecord',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Phase'),
        ),
        migrations.AddField(
            model_name='districtrecord',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='districtdetailrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Organization'),
        ),
        migrations.AddField(
            model_name='districtdetailrecord',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Phase'),
        ),
        migrations.AddField(
            model_name='districtdetailrecord',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoryrecord',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.District'),
        ),
        migrations.AddField(
            model_name='categoryrecord',
            name='district_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.DistrictDetail'),
        ),
        migrations.AddField(
            model_name='categoryrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Organization'),
        ),
        migrations.AddField(
            model_name='categoryrecord',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Phase'),
        ),
        migrations.AddField(
            model_name='categoryrecord',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
