# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_record_current_month_project_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtrecord',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.Category'),
            preserve_default=False,
        ),
    ]
