# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-07 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20180327_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtrecord',
            name='district_detail',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='production.DistrictDetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='big_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_bigtype', to='production.BigType'),
        ),
        migrations.AlterField(
            model_name='categoryrecord',
            name='bigtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.BigType'),
        ),
        migrations.AlterField(
            model_name='categoryrecord',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryrecord_category', to='production.Category'),
        ),
        migrations.AlterField(
            model_name='record',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_district', to='production.District'),
        ),
    ]
