# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-08 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20180407_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtdetailrecord',
            name='organization',
        ),
        # migrations.AddField(
        #     model_name='districtrecord',
        #     name='district_detail',
        #     field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='production.DistrictDetail'),
        #     preserve_default=False,
        # ),
        # migrations.RemoveField(
        #     model_name='districtrecord',
        #     name='district_detail',
        # ),
        migrations.AddField(
            model_name='districtdetailrecord',
            name='total_accumulative_contract_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='districtdetailrecord',
            name='total_accumulative_process_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='districtdetailrecord',
            name='total_current_month_contract_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='districtdetailrecord',
            name='total_current_month_process_payment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
